service:
  grpcServer:
    host: "localhost"
    port: 8081
    protocol: tcp

databases:
  mongoDB:
    host: "localhost"
    port: 27017
    username: "admin"
    password: "password"
    database: "base"

authCreditional:
  hmacSecret: test
  rsaSecret: test
  ecdsaSecret: test